repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks/
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.10
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

# -   repo: https://github.com/pycqa/pydocstyle/
#     rev: 6.3.0
#     hooks:
#     -   id: pydocstyle
#         args: [--convention=google, --add-ignore=D10]

-   repo: https://github.com/pre-commit/mirrors-mypy/
    rev: v1.19.1
    hooks:
    -   id: mypy

-   repo: local
    hooks:
    -   id: unittests
        name: run unittests
        entry: python -m unittest
        language: system
        pass_filenames: false
