[project]
name = "heval"
# version = ""
description = "Medical calculator for intensive care unit"
readme = "README.md"
requires-python = ">=3.8.10"
license = "GPL-3.0-or-later"
authors = [
    { name = "Eugene Dvoretsky", email = "radioxoma@gmail.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Medical Science Apps",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
]

[gui-scripts]
heval = "heval.__main__:main"

[project.urls]
Homepage = "https://github.com/radioxoma/heval"

[project.optional-dependencies]
test = [
    "mypy",
    "black",
    "isort",
]

dev = [
    "pre-commit",
]
