name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:  # Latest Windows 7 compatible binary release from python.org
          python-version: "3.8.10"
          architecture: x86
      - run: python -m unittest -v
      - name: Install packaging dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - run: .\build.bat
      - uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
          # draft: true
          fail_on_unmatched_files: true
  release-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python -m unittest -v
      - name: Install packaging dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - run: ./build_osx.sh
      - uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
          # draft: true
          fail_on_unmatched_files: true
